default_language_version:
  python: python3.11.6

repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      files: ^(src/)
      args: [--ignore-missing-imports]
      additional_dependencies:
        - "pydantic>=1.10.4"
        - "types-setuptools>=69.0.0.0"
